### ISSUE TITLE
Does this project support tif directories?

### ISSUE THREAD

**Issue by ricochet2200** [chai2010/tiff#3]
Does this project support tif directories as specified [here](http://www.libtiff.org/libtiff.html#Dirs)?  Basically it is just storing multiple images in the same tiff file.  It is very common for storing [pyramided images](http://iipimage.sourceforge.net/documentation/images/) which is common in Deep Zoom images for ultra high resolution images as well as medical images.

I see that you support bigtiff, but I see no way of specifying what directory you want (as I've done with the c library) and so I'm wondering if I'm missing something?  Thanks!

**Comment by chai2010** [comment]
Only support read at this moment.

list all ifd:
https://github.com/chai2010/tiff/blob/master/apps/tiffinfo.go

read subifd and multipages:
https://github.com/chai2010/tiff/blob/master/hello.go

**Comment by ricochet2200** [comment]
Thanks for the response, I'll have to check this out!
